EXPERIMENT:
  ID: "0825ntu" # Give your logs and model a unique name

##Data
DATA:
  TRANSFORM: False # If true, the points are pose-aligned before feeding to the model
  POSES: "no_poses" # Name of the pose file provided in each sequence folder
  SHUFFLE: False
  NUM_WORKER: 16
  DELTA_T_DATA: 0.1 # Time between scans in the dataset (0.1s for KITTI)
  VOXEL_SIZE: 0.1 # Used for discretization in x,y,z when creating a sparse tensor 
  SEMANTIC_CONFIG_FILE: "./config/wayside.yaml" 
  SPLIT:
    TRAIN:
      -
    VAL:
      -
    TEST:
      - 1
  DATAPATH: "/mydata/0825ntu/skitti-format/sequences/" #path/to/dataset/sequences
  OUTPUT: "/mydata/4DMOS_predictions/" #Output path of confidences
##Training
TRAIN:
  MAX_EPOCH: 60
  LR: 0.0001
  LR_EPOCH: 1
  LR_DECAY: 0.99
  WEIGHT_DECAY: 0.0001
  BATCH_SIZE: 1
  ACC_BATCHES: 1
  AUGMENTATION: True

##Network
MODEL:
  DELTA_T_PREDICTION: 0.1 # Temporal resolution of scans
  N_PAST_STEPS: 10
  WEIGHT: "/mydata/4dmos_ckpt/10_scans.ckpt"
C2L: #Confidence to label
  CONFIDENCEPATH: "/mydata/4DMOS_predictions/0825ntu/no_poses/" #PATH Before confidences
  STRATEGY: "bayes" #["non-overlapping", "bayes"]
  SEQUENCE: 
    - 1 #Test sequence
  PRIOR: 0.5 #Moving prior for bayesian fusing
  DT: 0.1 #Temporal resolution 